version: '3.8'

services:
  app:
    image: payment-gateway
    ports:
      - "8081:9090"
    restart: always

nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
        - app1
        - app2