version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: mongo_admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  payment-app:
    image: prod-payment-gateway
    container_name: payment-gateway
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8081:9090"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo_admin:mongo_admin@mongodb:27017/yourdb

volumes:
  mongo_data:
